### ISSUE TITLE
Unable to install with brew

### ISSUE THREAD

**Issue by tomfriedhof** [frigus02/kyml#30]
I'm getting this error message when trying to install with Home Brew

```
==> Installing kyml from frigus02/tap
Error: An exception occurred within a child process:
  TypeError: no implicit conversion of nil into String
```

Any ideas how to get around this?

**Comment by frigus02** [comment]
Hm. I don't have a Mac around at the moment. But the good new is: I can reproduce this in WSL.

I ran ` brew install --debug frigus02/tap/kyml` and can see in the backtrace that it comes from: https://github.com/frigus02/homebrew-tap/blob/dc158e5cf10d97741f3952f5a81aa7a14b263d04/kyml.rb#L20. It looks like `@bin_name` is nil.

This definitely worked before, though. And it's clearly downloading the correct file before that. So `@bin_name` _is_ set at some point. Hm...

**Comment by frigus02** [comment]
Reverting my commit https://github.com/frigus02/homebrew-tap/commit/dc158e5cf10d97741f3952f5a81aa7a14b263d04 fixes the issue. I'm sure I did this for a reason, but I can't remember what it was.

Anyway, since I can't remember, I did revert the commit. Can you try again (you might need to update the tap)? I hope it works now.
